name: Run Tests

on:
  pull_request:

jobs:
  validate:
    strategy:
      matrix:
        # Run in all these versions of Python
        # current and last three python versions
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    runs-on: ubuntu-latest
    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm install -g fauna-shell
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Run unit tests
      run:  python3 -m unittest discover

    - name: Setup Test Database
      run: ./test/setup.sh

    - name: Test sample app
      run: |
        FAUNA_ENDPOINT=http://localhost:8443 FAUNA_SECRET=`cat .fauna_key` python3 app.py > app.log 2>&1  &
        ./test/validate.sh
        cat app.log
